version: '3'

volumes:
  postgres-data: { }

networks:
  sample-project:
      driver: bridge

services:
  postgres-db:
    image: "postgres:14.1"
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5455:5432"
    env_file:
      - .config/.env
    networks:
      - sample-project

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.10
    volumes:
      - ./src:/app/src
    env_file:
      - .config/.env
    ports:
      - "8000:8000"
    command: start.sh run
    depends_on:
      - postgres-db
    networks:
      - sample-project

