# Generated by Django 4.2.14 on 2024-07-12 07:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('views', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='category.category', verbose_name='Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='city.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Advert',
                'verbose_name_plural': 'Adverts',
            },
        ),
    ]
